function makemex
%
% Function for generating gateway functions from MEX files for SLICOT System Identification Toolbox
% (Linux version, 64 bit).
% This file should be located in the directory containing the source MEX files, which is a subdirectory
% of the directory where the libraries slicot.a is located.
%
flags = 'FFLAGS="$FFLAGS -fPIC -fno-omit-frame-pointer -fdefault-integer-8" -largeArrayDims';
slident_mex_src = '';
xerbla    = 'xerbla.f';
libslicot = '../slicot.a';
slident_mex = {
    'findBD.f',  ...
    'ldsim.f',   ... 
    'onf2ss.f',  ...
    'order.f',   ...
    'sident.f',  ...
    'ss2onf.f',  ... 
    'wident.f',  ...
    'widentc.f', ...
    'Wiener.f',  ...
    };
%
for k = 1:length(slident_mex)
    file = slident_mex{k};
    fprintf( 'mex %s %s%s.f %s %s -lmwlapack -lmwblas\n', flags, slident_mex_src, file, xerbla, libslicot );
    eval( sprintf( 'mex %s %s%s.f %s %s -lmwlapack -lmwblas\n', flags, slident_mex_src, xerbla, file, libslicot ) );
end
